# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(287, 447)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.process_frame = QtWidgets.QFrame(self.centralwidget)
        self.process_frame.setGeometry(QtCore.QRect(10, 90, 271, 101))
        self.process_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.process_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.process_frame.setObjectName("process_frame")
        self.btn_process = QtWidgets.QPushButton(self.process_frame)
        self.btn_process.setGeometry(QtCore.QRect(10, 10, 141, 31))
        self.btn_process.setObjectName("btn_process")
        self.process_bar = QtWidgets.QProgressBar(self.process_frame)
        self.process_bar.setEnabled(False)
        self.process_bar.setGeometry(QtCore.QRect(70, 60, 191, 23))
        self.process_bar.setProperty("value", 24)
        self.process_bar.setObjectName("process_bar")
        self.label_2 = QtWidgets.QLabel(self.process_frame)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 51, 21))
        self.label_2.setObjectName("label_2")
        self.selec_file_frame = QtWidgets.QFrame(self.centralwidget)
        self.selec_file_frame.setGeometry(QtCore.QRect(10, 10, 271, 71))
        self.selec_file_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.selec_file_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.selec_file_frame.setObjectName("selec_file_frame")
        self.list_options = QtWidgets.QComboBox(self.selec_file_frame)
        self.list_options.setGeometry(QtCore.QRect(10, 30, 161, 31))
        self.list_options.setObjectName("list_options")
        self.list_options.addItem("")
        self.list_options.addItem("")
        self.list_options.addItem("")
        self.list_options.addItem("")
        self.label = QtWidgets.QLabel(self.selec_file_frame)
        self.label.setGeometry(QtCore.QRect(10, 0, 61, 21))
        self.label.setObjectName("label")
        self.btn_charge = QtWidgets.QPushButton(self.selec_file_frame)
        self.btn_charge.setGeometry(QtCore.QRect(180, 30, 81, 31))
        self.btn_charge.setObjectName("btn_charge")
        self.files_frame = QtWidgets.QFrame(self.centralwidget)
        self.files_frame.setGeometry(QtCore.QRect(10, 190, 271, 211))
        self.files_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.files_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.files_frame.setObjectName("files_frame")
        self.label_3 = QtWidgets.QLabel(self.files_frame)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 81, 21))
        self.label_3.setObjectName("label_3")
        self.list_new_file = QtWidgets.QListWidget(self.files_frame)
        self.list_new_file.setGeometry(QtCore.QRect(90, 10, 171, 192))
        self.list_new_file.setObjectName("list_new_file")
        self.selec_file_frame.raise_()
        self.process_frame.raise_()
        self.files_frame.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 287, 21))
        self.menubar.setObjectName("menubar")
        self.menuSUVECI = QtWidgets.QMenu(self.menubar)
        self.menuSUVECI.setObjectName("menuSUVECI")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuSUVECI.menuAction())

        self.retranslateUi(MainWindow)
        self.list_options.highlighted['QString'].connect(self.btn_charge.showMenu)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_process.setText(_translate("MainWindow", "PROCESS INFORMATION"))
        self.label_2.setText(_translate("MainWindow", "Processing"))
        self.list_options.setItemText(0, _translate("MainWindow", "File1"))
        self.list_options.setItemText(1, _translate("MainWindow", "File 2"))
        self.list_options.setItemText(2, _translate("MainWindow", "File 3"))
        self.list_options.setItemText(3, _translate("MainWindow", "File 4"))
        self.label.setText(_translate("MainWindow", "Select Files"))
        self.btn_charge.setText(_translate("MainWindow", "UPLOAD"))
        self.label_3.setText(_translate("MainWindow", "Files Expored:  "))
        self.menuSUVECI.setTitle(_translate("MainWindow", "SUVECI"))
